name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112849786.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t portfolio .
          docker tag portfolio:latest 471112849786.dkr.ecr.us-east-1.amazonaws.com/portfolio_docker_repository:latest
          docker push 471112849786.dkr.ecr.us-east-1.amazonaws.com/portfolio_docker_repository:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull 471112849786.dkr.ecr.us-east-1.amazonaws.com/portfolio_docker_repository:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio -p 3001:3000 471112849786.dkr.ecr.us-east-1.amazonaws.com/portfolio:latest
