name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          $(aws ecr get-login --no-include-email --region us-east-1)

      - name: Build and push Docker image
        run: |
          docker build -t portfolio .
          docker tag portfolio:latest <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/portfolio:latest
          docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/portfolio:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/portfolio:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio -p 3001:3000 <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/portfolio:latest
