name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.AWS_INSTANCE_SG_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v2w5z6p0

      - name: Build and push Docker image
        run: |
          docker build -t portfolio .
          docker tag portfolio:latest public.ecr.aws/v2w5z6p0/portfolio_docker_repository:latest
          docker push public.ecr.aws/v2w5z6p0/portfolio_docker_repository:latest

      - name: Get runer IP address
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_INSTANCE_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Testing SSH connection..."
            ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'
            docker pull public.ecr.aws/v2w5z6p0/portfolio_docker_repository:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio -p 3001:3000 public.ecr.aws/v2w5z6p0/portfolio_docker_repository:latest
          debug: true

      - name: Revoke runner ip address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
